language: php

sudo: false

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

cache:
  directories:
    - $HOME/.composer/cache/files

before_script:
  - composer install --no-interaction --no-progress --dev

script:
  - vendor/bin/phpunit --verbose --coverage-text
