dist: trusty

language: php

sudo: false

php:
  - 5.6
  - 7.1

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - phpenv config-rm xdebug.ini || true

install:
  - composer install --no-interaction --no-progress --prefer-dist

script:
  - composer validate
  - vendor/bin/phpunit
  - vendor/bin/php-cs-fixer --rules=@PSR2 --dry-run -v fix .
