dist: trusty

language: php

sudo: false

php:
  - 7.1

cache:
  directories:
    - $HOME/.composer/cache/files

before_script:
  - phpenv config-rm xdebug.ini || true
  - composer install --no-interaction --no-progress --prefer-dist

script:
  - composer validate
  - vendor/bin/phpunit
