language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  include:
    - php: 5.3
      env: PHPUNIT_FLAGS='--exclude-group sylius'
    - php: 5.4
      env: PHPUNIT_FLAGS='--exclude-group sylius'

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install --no-interaction --no-progress --prefer-dist

script:
  - vendor/bin/phpunit --verbose --coverage-text $PHPUNIT_FLAGS
