language: php

sudo: false

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install --no-interaction --no-progress --prefer-dist

script:
  - vendor/bin/phpunit --verbose --coverage-text
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "5.3" ] && [ "$TRAVIS_PHP_VERSION" != "5.4" ]; then php vendor/bin/phpunit --verbose --coverage-text --group=sylius; fi;'
