language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - phpenv config-rm xdebug.ini || true
  - composer install --no-interaction --no-progress --prefer-dist

script:
  - composer validate
  - vendor/bin/phpunit
